stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "Build Job"

test-code-job1:
  stage: test
  script:
    - echo "Test Job 1"

test-code-job2:
  stage: test
  script:
    - echo "Test Job 2"