domain: caskey-p1cbb.bahsoftwarefactory.com

istio:
  enabled: true

  ingressGateways:
    # public-ingressgateway:
    #   type: "NodePort"
    #   nodePortBase: 30000 

    public-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "kubernetes.io/cluster/c-m-n6rc24wl=owned,env=staging,ingress-type=public"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          # service.beta.kubernetes.io/aws-load-balancer-target-node-labels: "worker=true"

  gateways:
    public:
      ingressGateway: "public-ingressgateway"
      hosts:
      - "*.{{ .Values.domain }}"
      # autoHttpRedirect:
      #   enabled: true
      tls:
        # mode: PASSTHROUGH
        # key: ""
        # cert: ""
        key: ""
        cert: ""


  # -- Flux reconciliation overrides specifically for the Istio Package
  flux: {}

  # -- Values to passthrough to the istio-controlplane chart: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
  values: {}

  # -- Post Renderers.  See docs/postrenders.md
  postRenderers: []

jaegar: 
  enabled: false

kiali: 
  enabled: false

clusterAuditor:
  enabled: false

gatekeeper: 
  enabled: false

kyverno:
  enabled: false

kyvernopolicies:
  enabled: false

logging:
  enabled: false
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 256Mi
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
      data:
        count: 1
        persistence:
          size: 256Mi
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
    kibana:
      count: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi

eckoperator:
  enabled: false

fluentbit:
  enabled: false
  values:
    securityContext:
      privileged: true

promtail: 
  enabled: false

loki: 
  enabled: false

tempo:
  enabled: false

monitoring:
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi

twistlock:
  enabled: false
  values:
    console:
      persistence:
        size: 256Mi

addons: 
  
  argocd: 
    enabled: false

  authservice: 
    enabled: false
  
  minioOperator:
    enabled: false

  minio: 
    enabled: false
  
  gitlab:
    enabled: true
    hostnames:
      gitlab: gitlab
      registry: registry
    objectStorage: 
      type: "s3"
      endpoint: "https://s3.amazonaws.com"
      region: "us-east-1"
      bucketPrefix: "caskey-p1cbb"
      # accessKey: ""
      # accessSecret: ""
      iamProfile: "BSF_RKE2_ControlPlane_Role"
    values:
      # minio: 
      #   enabled: false
      gitlab:
        webservice:
          minReplicas: 1
          maxReplicas: 1
          helmTests:
            enabled: false
        gitlab-shell:
          minReplicas: 1
          maxReplicas: 1
        sidekiq:
          minReplicas: 1
          maxReplicas: 1
          toolbox:
        backups:
          objectStorage:
            config:
              secret: gitlab-object-storage
              key: backups
      # minio:
      #   enabled: false
      registry:
        bucket: caskey-p1cbb-gitlab-registry
      #   hpa:
      #     minReplicas: 1
      #     maxReplicas: 1
      global:
        appConfig:
          object_store:
            enabled: true
            # storage_options:
            #   server_side_encryption: aws:kms
            #   server_side_encryption_kms_key_id: arn:aws:kms:us-east-1:729651203190:alias/aws/s3
            connection: 
              secret: gitlab-object-storage
              key: rails
          artifacts: 
            bucket: caskey-p1cbb-backups-storage
          backups:
            bucket: caskey-p1cbb-gitlab-backups-storage
            tmpBucket: caskey-p1cbb-gitlab-tmp-storage
          dependencyProxy:
            bucket: caskey-p1cbb-gitlab-dependencyproxy-storage
          externalDiffs:
            bucket: caskey-p1cbb-gitlab-externaldiffs-storage
          lfs:
            bucket: caskey-p1cbb-gitlab-lfs-storage
          packages:
            bucket: caskey-p1cbb-gitlab-packages-storage
          terraformState:
            bucket: caskey-p1cbb-gitlab-terraformstate-storage
          uploads:
            bucket: caskey-p1cbb-gitlab-uploads-storage
          defaultCanCreateGroup: true
          enableUsagePing: true
          enableImpersonation: true
          defaultTheme: 11
          defaultProjectsFeatures:
            issues: true
            mergeRequests: true
            wiki: true
            snippets: true
            builds: true
            containerRegistry: true
          gitlab: 
            toolbox:
              backups:
                objectStorage:
                  config: 
                    secret: gitlab-object-storage
                    key: backups
          # omniauth:
          #   enabled: true
          #   allowSingleSignOn: ['saml', 'github']
          #   providers: 
          #     - secret: gitlab-github
          #     - secret: gitlab-keycloak
          # registry: 
          #   enabled: true
          #   storage:
          #     secret: gitlab-registry-storage
          #     key: config
  
  gitlabRunner: 
    enabled: true
  
  nexus:
    enabled: false
  
  sonarqube:
    enabled: false
  
  anchore:
    enabled: false
  
  mattermostoperator:
    enabled: false
  
  mattermost: 
    enabled: false
  
  velero:
    enabled: false
  
  keycloak:
    enabled: true
  
  vault: 
    enabled: true